In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
uploded = files.upload()

Saving ecommerce_sales_dataset.csv to ecommerce_sales_dataset (1).csv

In [ ]:
df = pd.read_csv('ecommerce_sales_dataset.csv')

In [ ]:
df.head(5)

,order_id,order_date,customer_id,city,region,payment_method,product_id,product_name,category,actual_price,discount_percentage,discounted_price,quantity,revenue,rating,rating_count
0,O000001,06-09-2024,C7265,Mumbai,East,UPI,P558,Hair Dryer,Beauty,1060,19.0,858.60,3,2575.80,4.6,3102
1,O000002,11-07-2023,C6051,Hyderabad,North,Net Banking,P413,Board Game,Toys,8522,26.0,6306.28,1,6306.28,4.9,2443
2,O000003,09-07-2023,C3734,NaN,East,Net Banking,P666,History Book,Books,8866,46.0,4787.64,4,19150.56,3.6,985
3,O000004,23-08-2024,C9433,Bangalore,North,Debit Card,P664,Running Shoes,Sports,3756,55.0,1690.20,3,5070.60,3.3,2445
4,O000005,04-02-2023,C4152,Delhi,South,Net Banking,P101,Mixer Grinder,Home Appliances,6435,51.0,3153.15,4,12612.60,3.2,2566

In [ ]:
df.shape

(7268, 16)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7268 entries, 0 to 7267
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   order_id             7268 non-null   object
 1   order_date           7268 non-null   object
 2   customer_id          7268 non-null   object
 3   city                 7265 non-null   object
 4   region               7268 non-null   object
 5   payment_method       7265 non-null   object
 6   product_id           7268 non-null   object
 7   product_name         7268 non-null   object
 8   category             7268 non-null   object
 9   actual_price         7268 non-null   int64
 10  discount_percentage  7266 non-null   float64
 11  discounted_price     7268 non-null   float64
 12  quantity             7268 non-null   int64
 13  revenue              7268 non-null   float64
 14  rating               7266 non-null   float64
 15  rating_count         7268 non-null   int64
dtypes: float64(4), int64(3), object(9)
memory usage: 908.6+ KB

In [ ]:
df.isnull().sum()

order_id               0
order_date             0
customer_id            0
city                   3
region                 0
payment_method         3
product_id             0
product_name           0
category               0
actual_price           0
discount_percentage    2
discounted_price       0
quantity               0
revenue                0
rating                 2
rating_count           0
dtype: int64

In [ ]:
df['rating'] = df.groupby('category')['rating'].transform(lambda x: x.fillna(x.median()))

In [ ]:
df['discount_percentage'] = df.groupby('category')['discount_percentage'].transform(lambda x: x.fillna(x.median()))

In [ ]:
df['payment_method'] = df['payment_method'].fillna(df['payment_method'].mode()[0])

In [ ]:
df['city'] = df['city'].fillna(df['city'].mode()[0])

In [ ]:
df.isnull().sum()

order_id               0
order_date             0
customer_id            0
city                   0
region                 0
payment_method         0
product_id             0
product_name           0
category               0
actual_price           0
discount_percentage    0
discounted_price       0
quantity               0
revenue                0
rating                 0
rating_count           0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.dtypes

order_id                object
order_date              object
customer_id             object
city                    object
region                  object
payment_method          object
product_id              object
product_name            object
category                object
actual_price             int64
discount_percentage    float64
discounted_price       float64
quantity                 int64
revenue                float64
rating                 float64
rating_count             int64
dtype: object

In [ ]:
df['order_date'] = pd.to_datetime(df['order_date'],format='%d-%m-%Y')

In [ ]:
df['order_date'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 7268 entries, 0 to 7267
Series name: order_date
Non-Null Count  Dtype
--------------  -----
7268 non-null   datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 56.9 KB

In [ ]:
df.columns

Index(['order_id', 'order_date', 'customer_id', 'city', 'region',
       'payment_method', 'product_id', 'product_name', 'category',
       'actual_price', 'discount_percentage', 'discounted_price', 'quantity',
       'revenue', 'rating', 'rating_count'],
      dtype='object')

Feature Engineering

In [ ]:
df['discount_amount'] = df['actual_price'] - df['discounted_price']
df['discount_amount'].head(5)

0     201.40
1    2215.72
2    4078.36
3    2065.80
4    3281.85
Name: discount_amount, dtype: float64

In [ ]:
df['order_month'] = df['order_date'].dt.month

df['order_month'].head(5)

0    9
1    7
2    7
3    8
4    2
Name: order_month, dtype: int32

In [ ]:
df['order_year'] = df['order_date'].dt.year

df['order_year'].head(5)

0    2024
1    2023
2    2023
3    2024
4    2023
Name: order_year, dtype: int32

Exploratory Data Analysis (EDA)

In [ ]:
df.groupby('category')['revenue'].sum().sort_values(ascending=False)

category
Electronics        8296223.60
Toys               8284427.33
Home Appliances    8014052.29
Clothing           7855915.66
Books              7850764.51
Furniture          7792609.26
Sports             7422106.14
Beauty             7265384.06
Name: revenue, dtype: float64

In [ ]:
df.groupby('region')['revenue'].sum()

region
East     14600226.14
North    16015249.42
South    15979914.76
West     16186092.53
Name: revenue, dtype: float64

In [ ]:
df['payment_method'].value_counts()

payment_method
Debit Card          1520
Net Banking         1479
Cash on Delivery    1441
Credit Card         1429
UPI                 1399
Name: count, dtype: int64

In [ ]:
df.groupby('product_name')['revenue'].sum().sort_values(ascending=False).head(5)

product_name
Gaming Mouse       1816203.70
Study Table        1800300.19
Electric Kettle    1782298.12
Building Blocks    1780272.25
Power Bank         1778635.99
Name: revenue, dtype: float64

In [ ]:
df.groupby('city')['revenue'].sum().sort_values(ascending=False).head(10)

city
Pune         8411425.74
Delhi        8290412.54
Kolkata      8267416.90
Chennai      7868916.56
Hyderabad    7630315.54
Mumbai       7456525.26
Ahmedabad    7449937.40
Bangalore    7406532.91
Name: revenue, dtype: float64

In [ ]:
df.groupby('order_month')['revenue'].sum()

order_month
1     4881891.33
2     5018181.60
3     4939268.09
4     5166098.98
5     5146758.14
6     5394991.21
7     5444760.28
8     5423848.17
9     5070492.85
10    5625857.68
11    5230652.33
12    5438682.19
Name: revenue, dtype: float64

In [ ]:
df.groupby('category')['rating'].mean().sort_values(ascending=False)

category
Beauty             4.017218
Furniture          4.013817
Sports             4.009070
Books              4.001985
Toys               4.001814
Clothing           3.986889
Electronics        3.974074
Home Appliances    3.965664
Name: rating, dtype: float64

In [ ]:
df.to_csv("clean_ecommerce_data.csv", index=False)

In [ ]:
from google.colab import files
files.download("clean_ecommerce_data.csv")